# Generated by Django 5.2.12 on 2026-03-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="display_name",
        ),
    ]
